version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/calculator/
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: deploy_scripts/install.sh
      runas: ec2-user
  ApplicationStop:
    - location: deploy_scripts/stop.sh
      runas: ec2-user
  ApplicationStart:
    - location: deploy_scripts/start.sh
      runas: ec2-user
  ValidateService:
    - location: deploy_scripts/validate.sh
      runas: ec2-user
